### ISSUE TITLE
Export rules from table

### ISSUE THREAD

**Issue by jKh98** [seanpmaxwell/Trool#2]
Hello, 
I was wondering if there is any feature to export or read rules that are already in the .csv file. This would save a lot of time and handling when attempting to read the table on our own.

**Comment by seanpmaxwell** [comment]
You mean actually export the Datatable objects that are generated from reading the CSV file?

**Comment by jKh98** [comment]
Yes, I am trying to automate rule generation based on API requests, and considering these rules are saved in the csv file, I was wondering if there is a way to extract then. This way all saved rules can be extracted when for example a get request is sent. I guess the feature is not available since I am using the library in a different way than originally intended.

**Comment by seanpmaxwell** [comment]
I created two new methods for version 1.1.0 'init' and a getter for 'decisionTables'. Call init() then you will have access to all the decision tables. Sorry for the long wait. Been working on another big project.
