### ISSUE TITLE
Improvement: Reusing internal state across calls

### ISSUE THREAD

**Issue by anuraagvaidya** [seanpmaxwell/Trool#3]
Hey there,

Thank you for such an amazing library.

We gave this a try and it works quite well, but we want to make sure that it can scale up as the ruleset size increases and the request-load increases, how would this tolerate load.

Would it be better to load the CSV just once, return an instance object, and then let the user call `applyRules` as many times as needed? This will reduce reading the file from a disk again and again on every evaluation call.

Let me know what you think.
Cheers, Anuraag.

**Comment by seanpmaxwell** [comment]
Done. Please see version 1.1.0
