### ISSUE TITLE
Trool status

### ISSUE THREAD

**Issue by sinisarudan** [seanpmaxwell/Trool#4]
A question:
- what is the status of the Trool project? is it still actively maintained ? 
I understand that the main goal of theprject is reached so that there is no need for further dev, yet if there are some community needs, or some bugs found, is there still some support?
- additionally if some of us want to continue work on it, improve it, is there a help from creators  available to answer on some questions to understand the code?

**Comment by seanpmaxwell** [comment]
I still actively maintain this project.
