### ISSUE TITLE
Capability to handle rules with AND /OR 

### ISSUE THREAD

**Issue by lthomas-pure** [seanpmaxwell/Trool#6]
I was wondering if Trools has the capability to configure a rule in CSV that has an AND / OR.

( variable1 = 1 and variable1 = 2 ) OR ( variable3 = 3 and variable4 = 4 ).

Drools a similar rule engine has a feature called ACTIVATION-GROUP to stop execution if one rule in the same activation group evaluates to T.

**Comment by seanpmaxwell** [comment]
Hmmm, could you give a scenario where this might be advantageous over just using multiple conditions?

**Comment by lthomas-pure** [comment]
I am new to trools so I am not sure if this can already be handled. I want to do the below Action/Condition. If I split into multiple conditions then I will get the same message twice.

Action: ( Alarm = NO and propertvalue > 1M ) OR ( alarm = Yes and propertvalue > 2M ).  
Condition: return a message "Property cannot be accepted."

**Comment by seanpmaxwell** [comment]
There currently is no built in ways to handle OR statements on a single row, maybe that's a feature I could add later. But I'm wondering, instead of sending the message an an action, could you maybe have a 'propertyAcceptable' setter and only send a message after all the facts are updated?

**Comment by seanpmaxwell** [comment]
Closing cause no response for 3 years
