### ISSUE TITLE
Compare 2 facts in a rule

### ISSUE THREAD

**Issue by charlescolbourn** [seanpmaxwell/Trool#7]
Hi,
I'm trying to find a way to compare 2 facts. So for example if I have

priceOne
priceTwo

and I want a rule to use whichever price is lower. If rules have to be of the form

fact (operator) $param

where param is specified in the table, I don't think I can do that?
thanks

**Comment by seanpmaxwell** [comment]
I think you could use the Imports option (imports from memory not the csv). Set an import value use the the Fact object (before passing the facts and imports into applyRules() ) and for the cell value (in the csv do) ImportName.lowerVal and ImportName.higherVal
